version: 2
jobs:
  build:
    docker:
      - image: tozd/meteor-testing:ubuntu-xenial
    environment:
      - METEOR_ALLOW_SUPERUSER: true
      - CIRCLE_TEST_REPORTS: /tmp/test-results
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: tests/authors/check-authors.sh
      - run:
          command: |
            # No merge marks in commits.
            ! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep '^'
      - run:
          command: npm install --unsafe-perm cli-real-favicon
          working_directory: /
      - run: meteor npm install --unsafe-perm
      - run: xvfb-run -s "-screen 0 1280x1024x24" tests/test-runner/test-all.sh
      - run: /node_modules/.bin/real-favicon check-for-update --fail-on-update public/version.json
      - store_test_results:
          path: /tmp/test-results
